# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEaWjdU-LOHvSZfVkYlBhGksLVPDwAVT
"""

import pandas as pd

class DataCleaning:

  # contruct class
  def __init__(self, p1, p2):
    pass