# -*- coding: utf-8 -*-
"""database_utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pVopk23tBWehAGzbTK09l5Sr1X0liLnA
"""

import yaml
import pandas as pd
import psycopg2
from sqlalchemy import create_engine
from sqlalchemy import inspect

class DatabaseConnector:

  # contruct class
  def __init__(self):
    pass

  def read_db_creds(self, filename):
    with open(filename, "r") as db_creds:
      return yaml.safe_load(db_creds)

  def init_db_engine(self, cred):
    DATABASE_TYPE = 'postgresql'
    DBAPI = 'psycopg2'
    engine = create_engine(f"{'postgresql'}+{'psycopg2'}://{cred['RDS_USER']}:{cred['RDS_PASSWORD']}@{cred['RDS_HOST']}:{cred['RDS_PORT']}/{cred['RDS_DATABASE']}")
    return engine

  def list_db_tables(self, engine):
    inspector = inspect(engine)
    return inspector.get_table_names()