# -*- coding: utf-8 -*-
"""data_extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T0ktQEuI2q6liyulA7NvQ8YMdACiF1V-
"""

import yaml
import pandas as pd
from sqlalchemy import inspect

class DataExtractor:

  # contruct class
  def __init__(self):
    pass

  def read_rds_table(self, engine, table_name):
    with engine.connect() as connection:
      return pd.read_sql_table(table_name, connection)